# Translations template for heat.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the heat project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: heat 5.0.1.dev80\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-01-18 06:35+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: heat/api/aws/ec2token.py:199
msgid "Ec2Token authorization failed, no auth_uri specified in config file"
msgstr ""

#: heat/api/aws/utils.py:99
#, python-format
msgid "Request does not contain %s parameter!"
msgstr ""

#: heat/api/cloudwatch/watch.py:253
msgid "Request does not contain required MetricData"
msgstr ""

#: heat/common/context.py:204
msgid "Keystone v3 API connection failed, no password trust or auth_token!"
msgstr ""

#: heat/common/exception.py:69
msgid "Exception in string format operation"
msgstr ""

#: heat/common/exception.py:71
#, python-format
msgid "%(name)s: %(value)s"
msgstr ""

#: heat/common/heat_keystoneclient.py:131
#: heat/common/heat_keystoneclient.py:212
msgid "Domain admin client authentication failed"
msgstr ""

#: heat/common/heat_keystoneclient.py:157
#: heat/common/heat_keystoneclient.py:359
msgid "Keystone client authentication failed"
msgstr ""

#: heat/common/heat_keystoneclient.py:163
msgid "trust token re-scoping failed!"
msgstr ""

#: heat/common/heat_keystoneclient.py:167
msgid "Trust impersonation failed"
msgstr ""

#: heat/common/heat_keystoneclient.py:282
#: heat/common/heat_keystoneclient.py:344
#, python-format
msgid "Failed to add user %(user)s to role %(role)s, check role exists!"
msgstr ""

#: heat/common/lifecycle_plugin_utils.py:46
msgid "failed to get lifecycle plug point classes"
msgstr ""

#: heat/common/lifecycle_plugin_utils.py:53
#, python-format
msgid "failed to instantiate stack lifecycle class %s"
msgstr ""

#: heat/common/lifecycle_plugin_utils.py:58
msgid "failed to sort lifecycle plug point classes"
msgstr ""

#: heat/common/lifecycle_plugin_utils.py:111
#, python-format
msgid "%(opname)s %(ci)s failed for %(a)s on %(sid)s"
msgstr ""

#: heat/common/plugin_loader.py:100
#, python-format
msgid "Failed to import module %s"
msgstr ""

#: heat/common/wsgi.py:291
msgid "SIGTERM received"
msgstr ""

#: heat/common/wsgi.py:301
msgid "SIGHUP received"
msgstr ""

#: heat/common/wsgi.py:440
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr ""

#: heat/common/wsgi.py:856
#, python-format
msgid "Exception handling resource: %s"
msgstr ""

#: heat/common/wsgi.py:878
#, python-format
msgid "Returning %(code)s to user: %(explanation)s"
msgstr ""

#: heat/common/wsgi.py:952
#, python-format
msgid "Unexpected error occurred serving API: %s"
msgstr ""

#: heat/engine/api.py:43
msgid "Timeout conversion failed"
msgstr ""

#: heat/engine/api.py:424
msgid "Unexpected number of keys in watch_data.data!"
msgstr ""

#: heat/engine/environment.py:659
#, python-format
msgid "Failed to read %s"
msgstr ""

#: heat/engine/environment.py:671
#, python-format
msgid "Failed to parse %(file_path)s"
msgstr ""

#: heat/engine/environment.py:675
#, python-format
msgid "Failed to read %(file_path)s"
msgstr ""

#: heat/engine/plugin_manager.py:95
#, python-format
msgid "Failed to load %(mapping_name)s from %(module)s"
msgstr ""

#: heat/engine/plugin_manager.py:102
#, python-format
msgid "Invalid type for %(mapping_name)s from %(module)s"
msgstr ""

#: heat/engine/resource.py:642
msgid "Error marking resource as failed"
msgstr ""

#: heat/engine/resource.py:1321 heat/engine/resource.py:1367
#: heat/engine/resource.py:1395
#, python-format
msgid "DB error %s"
msgstr ""

#: heat/engine/resource.py:1400
#, python-format
msgid ""
"Error acquiring lock for resource id:%(resource_id)s withatomic "
"key:%(atomic_key)s,engine_id:%(rs_engine_id)s/%(engine_id)s"
msgstr ""

#: heat/engine/resource.py:1646
#, python-format
msgid "signal %(name)s : %(msg)s"
msgstr ""

#: heat/engine/service.py:128
msgid "Unhandled error in asynchronous task"
msgstr ""

#: heat/engine/service.py:386
#, python-format
msgid "Failed to stop engine service, %s"
msgstr ""

#: heat/engine/service.py:1218 heat/engine/service.py:1270
#, python-format
msgid "Error loading resource type %s from global environment."
msgstr ""

#: heat/engine/service.py:1646
msgid "Filtering by namespace/metric not yet supported"
msgstr ""

#: heat/engine/service.py:1794
#, python-format
msgid "Service %(service_id)s update failed: %(error)s"
msgstr ""

#: heat/engine/service.py:1871
#, python-format
msgid "Error while resetting stack: %s"
msgstr ""

#: heat/engine/service_stack_watch.py:75
#, python-format
msgid "Unable to retrieve stack %s for periodic task"
msgstr ""

#: heat/engine/stack.py:83
#, python-format
msgid "Unexpected exception in %(func)s: %(msg)s"
msgstr ""

#: heat/engine/stack.py:678
#, python-format
msgid "Exception: %s"
msgstr ""

#: heat/engine/stack.py:1166
#, python-format
msgid "Unexpected action %s passed to update!"
msgstr ""

#: heat/engine/stack.py:1444
#, python-format
msgid "Unexpected action %s passed to delete!"
msgstr ""

#: heat/engine/stack.py:1650
#, python-format
msgid "Resource %(name)s delete failed: %(ex)s"
msgstr ""

#: heat/engine/stack.py:1659
#, python-format
msgid "Resource %(name)s create failed: %(ex)s"
msgstr ""

#: heat/engine/worker.py:90
#, python-format
msgid "%(topic)s is failed to stop, %(exc)s"
msgstr ""

#: heat/engine/clients/os/zaqar.py:40
msgid "Zaqar connection failed, no auth_token!"
msgstr ""

#: heat/engine/resources/stack_resource.py:436
msgid "update_stack"
msgstr ""

#: heat/engine/resources/wait_condition.py:73
#, python-format
msgid "Metadata failed validation for %s"
msgstr ""

#: heat/engine/resources/aws/autoscaling/autoscaling_group.py:309
msgid "Failed sending error notification"
msgstr ""

#: heat/engine/resources/aws/ec2/eip.py:116
msgid ""
"No default floating IP pool configured. Set 'default_floating_pool' in "
"nova.conf."
msgstr ""

#: heat/engine/resources/aws/ec2/eip.py:339
#: heat/engine/resources/aws/ec2/eip.py:362
msgid "Port not specified."
msgstr ""

#: heat/engine/resources/openstack/heat/remote_stack.py:153
#, python-format
msgid "exception: %s"
msgstr ""

#: heat/engine/resources/openstack/nova/nova_floatingip.py:82
msgid ""
"Could not allocate floating IP. Probably there is no default floating IP "
"pool is configured."
msgstr ""

